<?php

namespace PHPCore\SimpleHtmlDom\Tests;

/**
 * Tests for debug information generated by the parser
 */
class DebugInfoTest extends BaseTest
{
	/** @dataProvider dataProvider_for_print_r */
	public function test_print_r($expected, $html)
	{
		$this->html->load($html);
		$this->assertEquals($expected, print_r($this->html, true));
	}

	public function dataProvider_for_print_r(): array
	{
		return [
			'should return __debugInfo' => [
				'expected' => file_get_contents(TEST_DATA_PATH . '/debug_info/print_r_expected.txt'),
				'html'     => file_get_contents(TEST_DATA_PATH . '/debug_info/print_r_testdata.html'),
			],
		];
	}
}
